DROP DATABASE IF EXISTS songs_db;

CREATE DATABASE songs_db;

USE songs_db;

CREATE TABLE songs (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(50) NOT NULL,
  artist VARCHAR(50) NOT NULL
);
