DROP DATABASE IF EXISTS media_db;

CREATE DATABASE media_db;

USE media_db;

CREATE TABLE songs (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(50) NOT NULL,
  artist VARCHAR(50) NOT NULL
);
